### ISSUE TITLE
Research Information/Fix up UI

### ISSUE THREAD

**Issue by Wolfehh** [Wolfehh/TeamO#21]
- Not being hardcoded and not having it repeat the same information (onCreate issues basically)
- Fix up UI to make it look uniform (more buttons arent the same)
- Hardcoded "you have notifications"

**Comment by zoepeanut** [comment]
Today, I spent about 1.5 hours researching the use of gson/shared preferences that were added to allow us to more permanently clear notifications from the Twitter notifications activity, as well as coding in my own additions to update the UI to hide elements that are not relevant when the user has no notifications from a specific source. This will need to be updated (elements can potentially clear from main before they are cleared in the second activity, preventing user from returning despite still having uncleared notifications).  I will continue to update this over the next week to try and resolve this issue.

**Comment by zoepeanut** [comment]
Just spent about 15 more minutes working out how to save uncleared notifications in the main activity as well.
