### ISSUE TITLE
Fix the no duplicates

### ISSUE THREAD

**Issue by Wolfehh** [Wolfehh/TeamO#38]
Edit the way it saves in order to include duplicates from main activity.
Ideas we had:
Print all the duplicates
Or make it print how many times the same notification has printed

**Comment by zoepeanut** [comment]
This has been updated to print all duplicates now. I spent about 30 minutes on this task and it should be ready for review.

**Comment by zoepeanut** [comment]
I spent about 20 minutes eliminating extra arraylists
